#include "sieda/Export.hpp"

#include <cctype>
#include <cmath>
#include <cstdio>
#include <map>
#include <set>
#include <sstream>
#include <tuple>
#include <vector>

#include "sieda/Simulator.hpp"
#include "sieda/Units.hpp"

namespace sieda {

namespace {
std::string spiceNode(const Schematic& sch, PinRef pin) {
    int n = sch.netOf(pin);
    if (n < 0) return "NC_" + std::to_string(pin.component) + "_" + std::to_string(pin.pin);
    const Net& net = sch.nets()[static_cast<size_t>(n)];
    if (net.isGround) return "0";
    std::string s = net.name;
    for (char& c : s)
        if (!std::isalnum(static_cast<unsigned char>(c)) && c != '_') c = '_';
    return s;
}

std::string spiceSource(const std::string& value) {
    auto spec = SourceSpec::parse(value);
    if (!spec) return "DC 0";
    char buf[160];
    switch (spec->kind) {
        case SourceSpec::Kind::DC: std::snprintf(buf, sizeof buf, "DC %g", spec->dc); break;
        case SourceSpec::Kind::Sine:
            std::snprintf(buf, sizeof buf, "SIN(%g %g %g)", spec->offset, spec->amplitude, spec->frequency);
            break;
        case SourceSpec::Kind::Pulse:
            std::snprintf(buf, sizeof buf, "PULSE(%g %g 0 1n 1n %g %g)", spec->v1, spec->v2, spec->period * spec->duty,
                          spec->period);
            break;
    }
    return buf;
}

std::string mm(double v) {
    char b[32];
    std::snprintf(b, sizeof b, "%.4f", v);
    return b;
}

std::string footprintLabel(const Component& c) {
    const FootprintDef* fp = Library::instance().footprint(c.def().footprint);
    if (!fp) return c.def().footprint;
    return fp->label.empty() ? fp->name : fp->label;
}

std::string csvEscape(const std::string& s) {
    if (s.find_first_of(",\"\n") == std::string::npos) return s;
    std::string out = "\"";
    for (char c : s) out += c == '"' ? std::string("\"\"") : std::string(1, c);
    return out + "\"";
}
}  // namespace

std::string exportSpiceNetlist(const Schematic& sch, const std::string& title) {
    std::ostringstream o;
    o << "* " << (title.empty() ? "SiEDA design" : title) << "\n* Generated by SiEDA\n";
    std::set<std::string> models;
    for (const auto& c : sch.components()) {
        auto n = [&](int pin) { return spiceNode(sch, {c.id, pin}); };
        switch (c.kind) {
            case ComponentKind::Resistor: o << c.ref << " " << n(0) << " " << n(1) << " " << c.value << "\n"; break;
            case ComponentKind::Capacitor: o << c.ref << " " << n(0) << " " << n(1) << " " << c.value << "\n"; break;
            case ComponentKind::Inductor: o << c.ref << " " << n(0) << " " << n(1) << " " << c.value << "\n"; break;
            case ComponentKind::Fuse: o << "R" << c.ref << " " << n(0) << " " << n(1) << " 0.05 ; fuse " << c.value << "\n"; break;
            case ComponentKind::Switch: {
                bool on = c.value == "on" || c.value == "closed" || c.value == "1";
                o << "R" << c.ref << " " << n(0) << " " << n(1) << " " << (on ? "0.01" : "1G") << " ; switch\n";
                break;
            }
            case ComponentKind::VoltageSource: o << c.ref << " " << n(0) << " " << n(1) << " " << spiceSource(c.value) << "\n"; break;
            case ComponentKind::CurrentSource:
                // SPICE current flows from n+ through the source to n-; ours leaves "+", so swap nodes.
                o << c.ref << " " << n(1) << " " << n(0) << " " << spiceSource(c.value) << "\n";
                break;
            case ComponentKind::Diode:
                o << c.ref << " " << n(0) << " " << n(1) << " DSIEDA\n";
                models.insert(".model DSIEDA D(Is=2.52n N=1.752)");
                break;
            case ComponentKind::LED:
                o << c.ref << " " << n(0) << " " << n(1) << " DLED\n";
                models.insert(".model DLED D(Is=1e-18 N=2)");
                break;
            case ComponentKind::NPN:
                o << c.ref << " " << n(1) << " " << n(0) << " " << n(2) << " QSIEDA\n";
                models.insert(".model QSIEDA NPN(Is=1e-14 Bf=200 Br=1)");
                break;
            case ComponentKind::NMOS:
                o << c.ref << " " << n(1) << " " << n(0) << " " << n(2) << " " << n(2) << " MSIEDA\n";
                models.insert(".model MSIEDA NMOS(Vto=1.6 Kp=0.1 Lambda=0.01)");
                break;
            case ComponentKind::OpAmp:
                o << "X" << c.ref << " " << n(0) << " " << n(1) << " " << n(2) << " OPAMP_IDEAL\n";
                models.insert(".subckt OPAMP_IDEAL inp inn out\nE1 out 0 inp inn 1e6\n.ends");
                break;
            case ComponentKind::Connector:
            case ComponentKind::IC8:
            case ComponentKind::Custom:
                o << "* " << c.ref << " (" << c.def().name << ", " << c.value << ") has no SPICE model\n";
                break;
            default: break;
        }
    }
    for (const auto& m : models) o << m << "\n";
    o << ".op\n.end\n";
    return o.str();
}

std::string exportBomCsv(const Schematic& sch) {
    std::map<std::tuple<std::string, std::string, std::string>, std::vector<std::string>> groups;
    for (const auto& c : sch.components()) {
        if (!c.hasFootprint()) continue;
        groups[{c.def().name, c.value, footprintLabel(c)}].push_back(c.ref);
    }
    std::ostringstream o;
    o << "Item,Quantity,References,Type,Value,Footprint\n";
    int item = 1;
    for (const auto& [key, refs] : groups) {
        std::string joined;
        for (size_t i = 0; i < refs.size(); ++i) joined += (i ? " " : "") + refs[i];
        o << item++ << "," << refs.size() << "," << csvEscape(joined) << "," << csvEscape(std::get<0>(key)) << ","
          << csvEscape(std::get<1>(key)) << "," << csvEscape(std::get<2>(key)) << "\n";
    }
    return o.str();
}

std::string exportPickAndPlaceCsv(const Schematic& sch) {
    std::ostringstream o;
    o << "Designator,Value,Footprint,Mid X (mm),Mid Y (mm),Rotation,Layer\n";
    for (const auto& c : sch.components()) {
        if (!c.hasFootprint() || !c.pcb.placed) continue;
        o << c.ref << "," << csvEscape(c.value) << "," << csvEscape(footprintLabel(c)) << "," << mm(c.pcb.position.x) << ","
          << mm(c.pcb.position.y) << "," << c.pcb.rotation << "," << (c.pcb.bottom ? "Bottom" : "Top") << "\n";
    }
    return o.str();
}

static std::string exportGerberImpl(const Schematic& sch, const PcbLayout& pcb, GerberLayer layer, int copperIndex);

std::string exportGerber(const Schematic& sch, const PcbLayout& pcb, GerberLayer layer) {
    return exportGerberImpl(sch, pcb, layer, -1);
}

std::string exportCopperGerber(const Schematic& sch, const PcbLayout& pcb, int copperLayer) {
    return exportGerberImpl(sch, pcb, GerberLayer::TopCopper, copperLayer);
}

static std::string exportGerberImpl(const Schematic& sch, const PcbLayout& pcb, GerberLayer layer, int copperIndex) {
    const auto& s = pcb.settings;
    auto coord = [&](Vec2 p) {
        long long x = std::llround(p.x * 1e6), y = std::llround((s.height - p.y) * 1e6);
        return "X" + std::to_string(x) + "Y" + std::to_string(y);
    };
    std::ostringstream o;
    const char* names[] = {"Copper,L1,Top", "Copper,L2,Bot", "Soldermask,Top", "Soldermask,Bot", "Legend,Top", "Profile,NP"};
    o << "G04 SiEDA Gerber RS-274X*\n";
    o << "%TF.GenerationSoftware,SiEDA,SiEDA,1.0*%\n";
    const int bottom = pcb.settings.bottomLayer();
    if (copperIndex >= 0) {
        std::string side = copperIndex == 0 ? "Top" : (copperIndex == bottom ? "Bot" : "Inr");
        o << "%TF.FileFunction,Copper,L" << (copperIndex + 1) << "," << side << "*%\n";
    } else if (layer == GerberLayer::BottomCopper) {
        o << "%TF.FileFunction,Copper,L" << (bottom + 1) << ",Bot*%\n";
    } else {
        o << "%TF.FileFunction," << names[static_cast<int>(layer)] << "*%\n";
    }
    o << "%FSLAX46Y46*%\n%MOMM*%\n%LPD*%\n";

    std::map<std::string, int> apertures;
    std::ostringstream body;
    int nextAperture = 10;
    auto aperture = [&](const std::string& def) {
        auto it = apertures.find(def);
        if (it != apertures.end()) return it->second;
        apertures[def] = nextAperture;
        return nextAperture++;
    };
    auto circle = [&](double d) { return "C," + mm(d); };
    auto rect = [&](double w, double h) { return "R," + mm(w) + "X" + mm(h); };

    std::vector<std::pair<int, std::string>> ops;  // aperture, operation
    bool isCopper = layer == GerberLayer::TopCopper || layer == GerberLayer::BottomCopper;
    bool isMask = layer == GerberLayer::TopMask || layer == GerberLayer::BottomMask;
    int cl = copperIndex >= 0 ? copperIndex
             : ((layer == GerberLayer::TopCopper || layer == GerberLayer::TopMask) ? kTopLayer : bottom);
    if (copperIndex >= 0) isCopper = true;

    if (isCopper || isMask) {
        double grow = isMask ? 0.05 : 0.0;
        for (const auto& p : pcb.pads(sch)) {
            if (!p.onLayer(cl)) continue;
            int ap = aperture(p.round ? circle(p.size.x + 2 * grow) : rect(p.size.x + 2 * grow, p.size.y + 2 * grow));
            ops.push_back({ap, coord(p.position) + "D03*"});
        }
        for (const auto& v : pcb.vias) {
            if (isMask) continue;  // tented vias; through vias land on every copper layer
            ops.push_back({aperture(circle(v.diameter)), coord(v.position) + "D03*"});
        }
        if (isCopper) {
            for (const auto& t : pcb.tracks) {
                if (t.layer != cl) continue;
                int ap = aperture(circle(t.width));
                ops.push_back({ap, coord(t.a) + "D02*\n" + coord(t.b) + "D01*"});
            }
        }
    } else if (layer == GerberLayer::TopSilk) {
        int ap = aperture(circle(0.15));
        for (const auto& c : sch.components()) {
            if (!c.hasFootprint() || !c.pcb.placed || c.pcb.bottom) continue;
            Rect r = pcb.courtyard(c).inflated(-0.15);
            ops.push_back({ap, coord({r.x0, r.y0}) + "D02*\n" + coord({r.x1, r.y0}) + "D01*\n" + coord({r.x1, r.y1}) +
                                   "D01*\n" + coord({r.x0, r.y1}) + "D01*\n" + coord({r.x0, r.y0}) + "D01*"});
            // Pin-1 marker dot.
            const FootprintDef* fp = Library::instance().footprint(c.def().footprint);
            if (fp && !fp->pads.empty()) {
                Vec2 p1 = c.pcb.position + rotate90(fp->pads[0].offset, c.pcb.rotation);
                Vec2 dir = p1 - c.pcb.position;
                double len = dir.length();
                Vec2 mark = len > 1e-9 ? p1 + dir * (0.9 / len) : p1;
                ops.push_back({aperture(circle(0.3)), coord(mark) + "D03*"});
            }
        }
    } else {  // EdgeCuts
        int ap = aperture(circle(0.1));
        ops.push_back({ap, coord({0, 0}) + "D02*\n" + coord({s.width, 0}) + "D01*\n" + coord({s.width, s.height}) +
                               "D01*\n" + coord({0, s.height}) + "D01*\n" + coord({0, 0}) + "D01*"});
    }

    // Aperture definitions sorted by D-code.
    std::map<int, std::string> byCode;
    for (const auto& [def, code] : apertures) byCode[code] = def;
    for (const auto& [code, def] : byCode) {
        std::string type = def.substr(0, 1), params = def.substr(2);
        o << "%ADD" << code << type << "," << params << "*%\n";
    }
    int current = -1;
    for (const auto& [ap, op] : ops) {
        if (ap != current) {
            o << "D" << ap << "*\n";
            current = ap;
        }
        o << op << "\n";
    }
    o << "M02*\n";
    return o.str();
}

std::string exportExcellonDrill(const Schematic& sch, const PcbLayout& pcb) {
    std::map<std::string, std::vector<Vec2>> holes;  // diameter → positions
    auto key = [](double d) {
        char b[16];
        std::snprintf(b, sizeof b, "%.3f", d);
        return std::string(b);
    };
    for (const auto& p : pcb.pads(sch))
        if (p.throughHole && p.drill > 0) holes[key(p.drill)].push_back(p.position);
    for (const auto& v : pcb.vias) holes[key(v.drill)].push_back(v.position);

    std::ostringstream o;
    o << "M48\n; SiEDA Excellon drill file\nFMAT,2\nMETRIC,TZ\n";
    int tool = 1;
    for (const auto& [d, _] : holes) o << "T" << tool++ << "C" << d << "\n";
    o << "%\nG90\nG05\n";
    tool = 1;
    for (const auto& [d, pts] : holes) {
        o << "T" << tool++ << "\n";
        for (const auto& p : pts) o << "X" << mm(p.x) << "Y" << mm(pcb.settings.height - p.y) << "\n";
    }
    o << "T0\nM30\n";
    return o.str();
}

std::string exportStl(const Mesh& mesh, const std::string& name) {
    std::ostringstream o;
    o << "solid " << name << "\n";
    char buf[160];
    for (size_t t = 0; t + 2 < mesh.indices.size(); t += 3) {
        uint32_t i0 = mesh.indices[t], i1 = mesh.indices[t + 1], i2 = mesh.indices[t + 2];
        auto v = [&](uint32_t i) {
            return Vec3{mesh.positions[i * 3], mesh.positions[i * 3 + 1], mesh.positions[i * 3 + 2]};
        };
        Vec3 a = v(i0), b = v(i1), c = v(i2);
        Vec3 n = (b - a).cross(c - a);
        if (n.length() < 1e-12) continue;  // skip degenerate triangles
        n = n.normalized();
        std::snprintf(buf, sizeof buf, "facet normal %g %g %g\n", n.x, n.y, n.z);
        o << buf << " outer loop\n";
        for (const Vec3& p : {a, b, c}) {
            std::snprintf(buf, sizeof buf, "  vertex %g %g %g\n", p.x, p.y, p.z);
            o << buf;
        }
        o << " endloop\nendfacet\n";
    }
    o << "endsolid " << name << "\n";
    return o.str();
}

std::string exportObj(const Mesh& mesh, const std::string& name) {
    std::ostringstream o;
    o << "# SiEDA 3D export\no " << name << "\n";
    char buf[200];
    for (size_t i = 0; i < mesh.vertexCount(); ++i) {
        // Vertex colours as the widely supported "v x y z r g b" extension.
        std::snprintf(buf, sizeof buf, "v %g %g %g %.3f %.3f %.3f\n", mesh.positions[i * 3], mesh.positions[i * 3 + 1],
                      mesh.positions[i * 3 + 2], mesh.colors[i * 4], mesh.colors[i * 4 + 1], mesh.colors[i * 4 + 2]);
        o << buf;
    }
    for (size_t i = 0; i < mesh.vertexCount(); ++i) {
        std::snprintf(buf, sizeof buf, "vn %g %g %g\n", mesh.normals[i * 3], mesh.normals[i * 3 + 1], mesh.normals[i * 3 + 2]);
        o << buf;
    }
    for (size_t t = 0; t + 2 < mesh.indices.size(); t += 3) {
        uint32_t a = mesh.indices[t] + 1, b = mesh.indices[t + 1] + 1, c = mesh.indices[t + 2] + 1;
        if (a == b || b == c || a == c) continue;
        o << "f " << a << "//" << a << " " << b << "//" << b << " " << c << "//" << c << "\n";
    }
    return o.str();
}

}  // namespace sieda
