#!/usr/bin/env bash
# Rebuilds the example/test firmware (needs avr-gcc, avr-libc and the Arduino AVR core) and regenerates
# Core/src/FirmwareHex.inc.
set -euo pipefail
cd "$(dirname "$0")"
OUT=$(mktemp -d)
cc() { avr-gcc -mmcu="$1" -Os -std=gnu11 -Wall -o "$OUT/$2.elf" "$3"; avr-objcopy -O ihex -R .eeprom "$OUT/$2.elf" "$OUT/$2.hex"; }
cc atmega328p blink blink.c
cc atmega328p hello hello.c
cc atmega328p alu alu.c
cc atmega328p timer_isr timer_isr.c
cc atmega328p adc_pwm adc_pwm.c
cc atmega328p button button.c
cc attiny85 tiny_blink tiny_blink.c
# Arduino sketches against the real Arduino AVR core (Uno: ATmega328P, 16 MHz).
CORE=${ARDUINO_CORE:-/usr/share/arduino/hardware/arduino/avr}
FLAGS="-mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -Os -ffunction-sections -fdata-sections -I$CORE/cores/arduino -I$CORE/variants/standard"
mkdir -p "$OUT/core"
for f in "$CORE"/cores/arduino/*.c; do avr-gcc $FLAGS -std=gnu11 -c "$f" -o "$OUT/core/$(basename "$f").o"; done
for f in "$CORE"/cores/arduino/*.cpp; do avr-g++ $FLAGS -std=gnu++11 -fno-exceptions -fno-threadsafe-statics -c "$f" -o "$OUT/core/$(basename "$f").o"; done
for f in "$CORE"/cores/arduino/*.S; do avr-gcc $FLAGS -x assembler-with-cpp -c "$f" -o "$OUT/core/$(basename "$f").o"; done
avr-ar rcs "$OUT/core.a" "$OUT"/core/*.o
for sketch in sketches/*.ino; do
    name=$(basename "$sketch" .ino)
    { echo '#include <Arduino.h>'; cat "$sketch"; } > "$OUT/$name.cpp"
    avr-g++ $FLAGS -std=gnu++11 -fno-exceptions -fno-threadsafe-statics -c "$OUT/$name.cpp" -o "$OUT/$name.o"
    avr-gcc -mmcu=atmega328p -Os -Wl,--gc-sections -o "$OUT/$name.elf" "$OUT/$name.o" "$OUT/core.a" -lm
    avr-objcopy -O ihex -R .eeprom "$OUT/$name.elf" "$OUT/arduino_$name.hex"
done
{
    echo "// Generated by Core/tests/firmware/build.sh from Core/tests/firmware — Intel HEX images (do not edit)."
    for hex in "$OUT"/*.hex; do
        name=$(basename "$hex" .hex)
        echo "const char* const kHex_${name} ="
        tr -d '\r' < "$hex" | sed 's/.*/    "&\\n"/'
        echo "    ;"
    done
} > ../../src/FirmwareHex.inc
cp "$OUT"/*.hex "${KEEP_HEX:-$OUT}/" 2>/dev/null || true
echo "Built: $(ls "$OUT"/*.hex | xargs -n1 basename | tr '\n' ' ')"
